# Generated by Django 5.2.7 on 2025-10-23 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_cron', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cronjoblog',
            new_name='django_cron_code_89ad04_idx',
            old_name='django_cron_code_is_success_ran_at_time_idx',
        ),
        migrations.RenameIndex(
            model_name='cronjoblog',
            new_name='django_cron_code_21f381_idx',
            old_name='django_cron_code_start_time_ran_at_time_idx',
        ),
        migrations.RenameIndex(
            model_name='cronjoblog',
            new_name='django_cron_code_966ed3_idx',
            old_name='django_cron_code_start_time_idx',
        ),
    ]
