"""
Constants used throughout the chore application.
"""

# Point conversion constants
POINTS_TO_MONEY_CONVERSION_RATE = 100
POINT_VALUE_MULTIPLIER = 1

# Time constants
EARLY_BONUS_START_HOUR = 5

# Pagination constants
POINT_LOGS_PER_PAGE = 20
CHILD_POINT_LOGS_PER_PAGE = 10

# Leaderboard constants
LEADERBOARD_FIRST_PLACE_MULTIPLIER = 1
LEADERBOARD_SECOND_PLACE_MULTIPLIER = 2
LEADERBOARD_THIRD_PLACE_MULTIPLIER = 5

# Penalty constants
MAX_PENALTY_PERCENTAGE = 100
REJECTION_PENALTY = 100

# Chore availability constants
ALWAYS_AVAILABLE_TIME = 0

